### ISSUE TITLE
Problem creating machines - Error writing keys to file

### ISSUE THREAD

**Issue by bokazio** [yadutaf/docker-machine-driver-ovh#24] opened 2016-08-25 09:40 UTC
With the actual master i got the following problem while creating a new machine:

`(test) Calling .Create
(test) DBG | Checking Key Pair... map[Name:test-ff7803069a23febbe3f568ce007ed0b7aba4cfb92742276fcf53036983ea4ed8]
(test) DBG | Creating Key Pair... map[Name:test-ff7803069a23febbe3f568ce007ed0b7aba4cfb92742276fcf53036983ea4ed8]
Error creating machine: Error in driver during machine creation: Error writing keys to file(s): Unable to write file
notifying bugsnag: [Error creating machine: Error in driver during machine creation: Error writing keys to file(s): Unable to write file]`

This already happens with the default settings like `docker-machine -D create --driver ovh test
`
I used docker-machine version 0.8.1, build 41b3b25 with Docker version 1.12.0, build 8eab29e under Ubuntu 16.04.
If i go back to commit c474834ea333dea4456a1cfdd4871fba3a196494 its possible again to create a new machine.

**Comment by janeczku** [comment] 2016-10-02 13:19
The issue is that `d.SSHKeyPath` is always set to an empty string if `--ovh-ssh-key` flag is not specified.

https://github.com/yadutaf/docker-machine-driver-ovh/blob/2c1c34618a1e40cfd164cf9df2a053615f3d8a63/driver.go#L302-L305

**Comment by yadutaf** [comment] 2016-10-02 21:06
Thanks for the report. I'm sorry, I completely missed it the first time. As the is a fully benevolent work, If I'm not responsive withing a week or two, feel free to ping me :)

For the record, I (sadly) was able to easily reproduce the bug, here is the full debug log:

```
docker-machine --debug create -d ovh --ovh-project "Dev & Tests" test
Docker Machine Version:  0.7.0, build a650a40
Found binary path at /home/jean-tiare/dev/go/bin/docker-machine-driver-ovh
Launching plugin server for driver ovh
Plugin server listening at address 127.0.0.1:35138
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /home/jean-tiare/dev/go/bin/docker-machine-driver-ovh
Launching plugin server for driver ovh
Plugin server listening at address 127.0.0.1:34366
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(test) Calling .GetMachineName
(test) Calling .DriverName
(test) Calling .GetCreateFlags
(test) Calling .SetConfigFromFlags
Running pre-create checks...
(test) Calling .PreCreateCheck
(test) DBG | Validating project
(test) DBG | Found project id  ae0f4583c4b747e1964034a95102b42c
(test) DBG | Validating region
(test) DBG | Validating flavor
(test) DBG | Found flavor id  98c1e679-5f2c-4069-b4da-4a4f7179b758
(test) DBG | Validating image
(test) DBG | Found image id  d79802bf-0b36-47a4-acb6-76a293b0c037
(test) Calling .GetConfigRaw
Creating machine...
(test) Calling .Create
(test) DBG | Checking Key Pair... map[Name:test-c4fe0f63a3b9a0e56b2fa65d946c9a5710220b8c524d5e5097a631e167c85e0c]
(test) DBG | Creating Key Pair... map[Name:test-c4fe0f63a3b9a0e56b2fa65d946c9a5710220b8c524d5e5097a631e167c85e0c]
Error creating machine: Error in driver during machine creation: Error writing keys to file(s): Unable to write file
open : no such file or directory
notifying bugsnag: [Error creating machine: Error in driver during machine creation: Error writing keys to file(s): Unable to write file]
```

Please accept commit https://github.com/yadutaf/docker-machine-driver-ovh/commit/542fb3f083af56652dcbe77aeafb8d64c884b79d as a gift for the delay ;)

**Comment by yadutaf** [comment] 2016-10-02 21:22
Can you confirm this fixes the issue for you ?

**Comment by yadutaf** [comment] 2016-10-02 21:33
And, as you may have partially broken machines, you'll probably need https://github.com/yadutaf/docker-machine-driver-ovh/commit/dddc4eb23951e163dce6e16373a8649eaa1fcf02 too to clean them.

**Comment by janeczku** [comment] 2016-10-02 21:54
Hi @yadutaf, thanks for the fix! I'll test it out tomorrow.

**Comment by bokazio** [comment] 2016-10-04 08:38
Hi @yadutaf, can't confirm its working...
Still got the same error with standard settings (without ovh-ssh-key).
`Error creating machine: Error in driver during machine creation: Error writing keys to file(s): Unable to write file
notifying bugsnag: [Error creating machine: Error in driver during machine creation: Error writing keys to file(s): Unable to write file]`

THX in advance

**Comment by yadutaf** [comment] 2016-10-04 08:46
Strange... Did you try with https://github.com/yadutaf/docker-machine-driver-ovh/commit/4ce236f0554c605100e9cc5047aa29702776c143 ?

**Comment by bokazio** [comment] 2016-10-04 09:05
Ok, my fault.. thought its already in master...
Confirm its working! Thx

**Comment by yadutaf** [comment] 2016-10-04 09:43
\o/

**Comment by yadutaf** [comment] 2016-10-04 19:31
Fix merged. Thanks for the report.

**Closed as completed** 2016-10-04 19:30 UTC
